apiVersion: v1
kind: Service
metadata:
  name: containerinfo
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  namespace:  {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 5000
  selector:
    app: label-selector